### ISSUE TITLE
dependency to module hex is missing

### ISSUE THREAD

**Issue by elangelo** [gagle/node-binary-reader#1]
I would like to use binary-reader in a project of my own. You do seem to lack a dependency in package.json

i get this error when i require('binary-reader')
Error: Cannot find module 'hex'

seems like a trivial fix, so i didn't include a patch

**Comment by gagle** [comment]
Ok, fixed. But right now I cannot publish the new version to npm (https://github.com/isaacs/npm/issues/4302)

**Comment by gagle** [comment]
Done.
